# -*- coding: utf-8 -*-
"""yoga_pose_estimation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xIY3OjzAT5PBkjo4CS5ZabejOe3TI8m8
"""

#-- Mount Google Drive ---
from google.colab import drive
drive.mount('/content/drive')

## -- Set up the Dataset Path --
import os

DATASET_PATH = "/content/drive/MyDrive/yoga_pose_dataset/YogaPoses"

# Verify the Path
for label in sorted(os.listdir(DATASET_PATH)):
  label_dir = os.path.join(DATASET_PATH, label)
  if os.path.isdir(label_dir):
    count = len([f for f in os.listdir(label_dir)
                if f.lower().endswith((".jpg",".jpeg",".png"))])
    print(f" {label:25s} -> {count} images")

!pip install mediapipe

import os
import urllib.request

model_url = "https://storage.googleapis.com/mediapipe-models/pose_landmarker/pose_landmarker_full/float16/latest/pose_landmarker_full.task"
model_path = "/content/pose_landmarker.task"

if not os.path.exists(model_path):
    print("Downloading model...")
    urllib.request.urlretrieve(model_url, model_path)
    print(f"Downloaded: {os.path.getsize(model_path) / 1e6:.1f} MB")
else:
    print(f"Model already exists: {os.path.getsize(model_path) / 1e6:.1f} MB")

import mediapipe as mp
from mediapipe.tasks import python
from mediapipe.tasks.python import vision
import cv2, csv, os, glob
import numpy as np

# Setup detector
base_options = python.BaseOptions(model_asset_path="/content/pose_landmarker.task")
options      = vision.PoseLandmarkerOptions(base_options=base_options)
detector     = vision.PoseLandmarker.create_from_options(options)

header = ["label"] + [f"kp{i}_{c}" for i in range(33) for c in ["x","y","z","vis"]]
rows   = []
failed = []

for label in sorted(os.listdir(DATASET_PATH)):
    label_dir = os.path.join(DATASET_PATH, label)
    if not os.path.isdir(label_dir):
        continue

    img_paths = (glob.glob(f"{label_dir}/*.jpg")  +
                 glob.glob(f"{label_dir}/*.jpeg") +
                 glob.glob(f"{label_dir}/*.png"))

    print(f"Processing {label} ({len(img_paths)} images)...")

    for img_path in img_paths:
        img_cv = cv2.imread(img_path)
        if img_cv is None:
            failed.append(img_path)
            continue

        img_rgb = cv2.cvtColor(img_cv, cv2.COLOR_BGR2RGB)
        mp_img  = mp.Image(image_format=mp.ImageFormat.SRGB, data=img_rgb)
        result  = detector.detect(mp_img)

        if result.pose_landmarks:
            row = [label]
            for lm in result.pose_landmarks[0]:
                row += [lm.x, lm.y, lm.z, lm.visibility]
            rows.append(row)
        else:
            failed.append(img_path)

# Save CSV to both Colab and Drive so you don't lose it
csv_colab = "/content/landmarks.csv"
csv_drive = "/content/drive/MyDrive/yoga_dataset/landmarks.csv"

for csv_path in [csv_colab, csv_drive]:
    with open(csv_path, "w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(header)
        writer.writerows(rows)

print(f"\nSaved   : {len(rows)} rows")
print(f"Failed  : {len(failed)} images (no pose detected)")
print(f"CSV saved to Drive: {csv_drive}")

